version: '3.0'
services:
  server_container:
    container_name: server_container
    build:
      context: .
    env_file:
      - .env.production
    volumes:
      - ./app/node_modules
    ports:
      - 5000:5000
    command: npm run start
    restart: always
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: academy-project
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: